---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensores
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sensores
    spec:
      containers:
      - name: sensores
        image: onydarius/sensores:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: sensores
---
apiVersion: v1
kind: Service
metadata:
  name: sensores
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: sensores